name: mailtm_api
description: This package makes creating mail or temporary mail easier than ever. The mail.tm API wrapper is easy to use.
version: 1.1.0
repository: https://github.com/furkanbora239/mailtm_api

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
